; OCI IoT Platform demo - device configuration file
; Do NOT quote parameter values!

; Configuration file definition version
; This must align with the expected version (IOT_CONFIG_VERSION constant
; defined in config_manager.h)
[config]
version = 1

; Hardware configuration
[hardware]
; Port used by sensors (A or B) (Optional, default: B)
; i2c_port = B

; Display brightness in % (Optional, default: 40)
; display_brightness = 40

; Time before switching display backlight off (seconds) (Optional, default: 300)
; display_timeout = 300

; Wireless configuration
[wifi]
ssid =
password =

; MQTT configuration
[mqtt]
; IoT Domain device host and port (OCI IoT Platform only listens on port 8883)
host =
port = 8883
; File name of the CA certificate for the OCI IoT Platform in PEM format
; Should be DigiCert Global Root G2 certificate available at
; https://knowledge.digicert.com/general-information/digicert-trusted-root-authority-certificates
ca_cert = digicert-global-g2.pem

; The "externalKey" property of your Digital Twin.
; When using certificate authentication (mTLS), this must be the CN of the certificate
user =

; Authentication. Must be either a password or a certificate; password takes precedence.
; Password:
password =
; Certificate - Path to the client certificate and key in PEM format
; client_cert =
; client_key =

; Quality of Service (Optional, default: 0)
qos = 0

; Keep alive in seconds (Optional, default: 60)
keep_alive = 60

; Base MQTT topic
topic = iot/v1

; Publish frequency in seconds (Optional, default: 60)
publish_freq = 60

; OTA configuration
[ota]
; File name for the root CA certificate of the server hosting OTA updates
; If updates are stored on OCI Object Storage Buckets, it should be the
; "DigiCert Global Root G2" certificate
; If not specified, it defaults to the mqtt.ca_cert certificate
; ca_cert =
